Allow for distro/version specific assets
$asset_dir is set to the most specific asset dir available. For example,
if $linux is set to 'centos/6' and that dir exists, it will be used
instead of the dir 'centos' for package source files. This allows us to
drive the package config based on the distro+version if version specific
customizations are desired.

diff --git a/build_mesos b/build_mesos
--- a/build_mesos
+++ b/build_mesos
@@ -82,6 +82,15 @@ function main {
 
   src_dir=$(as_absolute "$src_dir")
   build_dir=$(as_absolute "$build_dir")
+
+  # Use the more specific dir, e.g. centos/6 will be used over centos if present
+  if [[ -d "$this/$linux" ]]
+  then asset_dir="$linux"
+  elif [[ -d "${linux%%/*}" ]]
+  then asset_dir="${linux%%/*}"
+  else err "Unable to determine asset_dir for $linux"; exit 1
+  fi
+
   if ! $prebuilt; then
     checkout
   fi
@@ -266,25 +275,23 @@ function find_gem_bin {
 }
 
 function deb_ {
-  local scripts="${linux%%/*}"
   local opts=( -t deb
                --deb-recommends zookeeper
                --deb-recommends zookeeperd
                --deb-recommends zookeeper-bin
                -d 'java7-runtime-headless | java6-runtime-headless'
                -d libcurl3
-               --after-install "$this/$scripts/mesos.postinst"
-               --after-remove "$this/$scripts/mesos.postrm" )
+               --after-install "$this/$asset_dir/mesos.postinst"
+               --after-remove "$this/$asset_dir/mesos.postrm" )
   rm -f "$this"/pkg.deb
   fpm_ "${opts[@]}" -p "$this"/pkg.deb
 }
 
 function rpm_ {
-  local scripts="${linux%%/*}"
   local opts=( -t rpm
                -d libcurl
-               --after-install "$this/$scripts/mesos.postinst"
-               --after-remove "$this/$scripts/mesos.postrm" )
+               --after-install "$this/$asset_dir/mesos.postinst"
+               --after-remove "$this/$asset_dir/mesos.postrm" )
   rm -f "$this"/pkg.rpm
   fpm_ "${opts[@]}" -p "$this"/pkg.rpm
 }
